#Change url to your domain. Leave localhost server or blank when working locally.
#port:                 4000
#host:                 localhost

baseurl:              http://hdlab.stanford.edu

#
# is this a lab site or project site?
type:                     lab
# Project or Lab name
name:                     "Humanities + Design"
shortname:                 hdlab
sub-name:                 "a Research Lab at Stanford University"
markdown:                 redcarpet
highlighter:              pygments
description: "We are a research lab at the Center for Spatial and Textual Analysis (CESTA), Stanford University."
category_dir:             lab-notebook
category_title_prefix :   'Lab Notebook: '
category_title :          'Lab Notebook'
google_id:                'UA-39616982-1'
disqus:                   'humanitiesplusdesign'
permalink:                /lab-notebook/:categories/:year/:month/:day/:title/
twitter:                   hdstanford
favicon:  "https://dl.dropboxusercontent.com/s/o0rhoh2bh2xu9uu/favicon.ico"
gems: [jekyll_figure]

collections:
  slides:
    output: true

